---
- hosts: servers
  become: true
  become_user: root

  # vars:
  #   # mysql_user: root
  #   # mysql_password: password
  #   edgar_database: edgar
  #   runtime_user: edgar

  tasks:
    - import_tasks: locale.yaml
    - import_tasks: updates.yaml
